version: 2

jobs:
  coditsu:
    machine: true
    steps:
      - checkout
      - run: \curl -sSL https://api.coditsu.io/run/ci | bash

workflows:
  version: 2
  build:
    jobs:
      - coditsu

  nightly:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - coditsu
