version: 2

jobs:
  specs:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
      - image: circleci/postgres:10.10-alpine-ram
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci_test
          POSTGRES_PASSWORD: ""

    environment:
      RAILS_ENV: test
      RACK_ENV: test
      POSTGRES_HOST: localhost
      RUBYGEMS_POSTGRES_USERNAME: circleci
      RUBYGEMS_POSTGRES_DB_NAME: circleci

    steps:
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-git-{{ .Branch }}-{{ .Revision }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-git-{{ .Branch }}-
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-git-
      - checkout
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-git-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{arch}}-gem-lock-{{ checksum "Gemfile.lock" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{arch}}-gem-lock-
      - run: |
          sudo apt-get update
          sudo apt install postgresql-client
          git config --global user.email "ci@coditsu.io"
          git config --global user.name "Coditsu CI"
          sudo rm -rf /usr/local/bin/bundle && gem install bundler
          bundle update --bundler
          yes | gem update --system || true
          bundle config github.https true
          bundle check --path=vendor/bundle || bundle install --path vendor/bundle
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{arch}}-gem-lock-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: cp config/databases/rubygems.yml.example config/databases/rubygems.yml
      - run: cp config/settings.yml.example config/settings.yml
      - run: cp .env.example .env
      - run: RAILS_ENV=test bundle exec rails app:schema:load
      - run: RAILS_ENV=test bundle exec rspec

  coditsu:
    machine: true
    steps:
      - checkout
      - run: \curl -sSL https://api.coditsu.io/run/ci | bash

workflows:
  version: 2
  build:
    jobs:
      - specs
      - coditsu

  nightly:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - coditsu
      - specs
